In [6]:
import numpy as np

In [5]:
print("K-nearest neighbor")

K-nearest neighbor


In [14]:
train_data=np.load('hw2_data/knn/train_data.npy')
train_data[0]

array([5.6, 2.9, 3.6, 1.3])

In [15]:
len(train_data)

250

In [21]:
train_labels = np.load('hw2_data/knn/train_labels.npy')
print(len(train_labels))
train_labels

250


array([1, 2, 1, 1, 1, 2, 1, 1, 1, 0, 2, 0, 1, 0, 1, 0, 1, 2, 1, 0, 1, 2,
       0, 1, 1, 1, 1, 1, 2, 2, 1, 0, 0, 1, 2, 2, 0, 2, 0, 0, 2, 2, 0, 2,
       1, 0, 2, 0, 2, 2, 0, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1, 0, 0,
       2, 2, 0, 2, 0, 0, 2, 2, 0, 2, 2, 0, 2, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       2, 0, 1, 0, 0, 1, 1, 2, 0, 1, 1, 2, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0,
       2, 0, 2, 2, 1, 0, 0, 1, 1, 0, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 0,
       1, 2, 2, 2, 0, 2, 1, 0, 0, 1, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 0, 0,
       1, 0, 0, 0, 2, 0, 2, 0, 0, 0, 1, 2, 2, 0, 2, 1, 1, 0, 1, 0, 2, 1,
       0, 1, 0, 1, 2, 0, 0, 1, 1, 2, 0, 1, 0, 1, 2, 0, 1, 1, 2, 1, 0, 2,
       0, 0, 2, 2, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 2, 1, 0, 2, 0, 1, 1, 2, 1, 1, 1, 0,
       2, 0, 1, 1, 0, 2, 0, 1])

In [24]:
test_data = np.load('hw2_data/knn/test_data.npy')
print(len(test_data))
test_data[0]

200


array([ 2.58965953,  2.96278592, -0.11994302, -0.06988396])

In [25]:
test_labels = np.load('hw2_data/knn/test_labels.npy')
test_labels

array([0, 1, 1, 2, 0, 0, 0, 1, 2, 0, 1, 0, 2, 2, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 2, 2, 0, 2, 2, 2, 0, 0, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 2, 2, 1,
       1, 0, 1, 1, 2, 1, 2, 2, 1, 1, 1, 0, 2, 2, 1, 0, 2, 0, 0, 2, 1, 0,
       2, 0, 2, 0, 0, 2, 2, 2, 0, 0, 2, 1, 0, 1, 1, 1, 0, 2, 2, 2, 2, 0,
       1, 2, 2, 2, 0, 2, 1, 1, 0, 1, 0, 0, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0,
       0, 0, 1, 2, 2, 1, 2, 1, 0, 2, 2, 0, 1, 1, 0, 0, 0, 2, 2, 0, 0, 0,
       2, 0, 0, 2, 1, 1, 0, 2, 2, 2, 2, 0, 2, 1, 2, 0, 0, 2, 2, 1, 1, 2,
       0, 1, 2, 2, 1, 2, 0, 2, 0, 1, 2, 2, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 2, 2, 1, 2, 1, 2, 2, 2, 0, 0, 2, 1, 1, 2, 1, 0, 0,
       0, 1])